language: python
cache: pip

python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"

install:
  - pip install -U pip
  - pip install tox-travis

script: tox

deploy:
  provider: pypi
  edge: true
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: master
    tags: true
